### ISSUE TITLE
Nunjucks is having a conflict with RactiveJS

### ISSUE THREAD

**Issue by Sturmkeks** [mozilla/nunjucks#1003]
I've been ordered to convert a existing project in my company from 'serve' to nunjucks, because we want to switch to something else, where I really wanted to use nunjucks, as I use it for private projects and I really love it.

The big problem I'm having here, is that I cannot build my project, because nunjucks gets confused with the RactiveJS syntax, which uses the moustache as well. So I'm pretty much stuck here and would appreciate any help given.

Link to RactiveJS: https://ractive.js.org/

Regards,
Some dude

**Comment by ArmorDarks** [comment]
You can change Nunjucks tags to use different syntax.

[Docs](https://mozilla.github.io/nunjucks/api.html#customizing-syntax)

But I'd say that it would be strange to use ReactiveJS with Nunjucks, since ReactiveJS is templating in some sense too. If it doesn't provide a native way to reconfigurate templating engine, I'd say that it would be quite bad idea, since you will lose a lot of ReactiveJS functionality and will constantly struggle with bindings.

**Comment by Sturmkeks** [comment]
I might have figured it out. I used the {% raw %} tag around the RactiveJS parts and it seems that it rendered it correctly into the html file. Even though it feels like a hack-ish workaround it does a good job.
I can't tell for sure though, because I'm still struggling with some file conversions. Converting a huge, finished project from 'serve' into nunjucks surely isn't fun at all!

@ArmorDarks Thank you for your help. If the raw-tag doesn't do it's job on this problem, I will try your method ;)

Cheers!

**Comment by Sturmkeks** [comment]
Yup, the {% raw %} tag did its job!
Closing the issue.
