### ISSUE TITLE
Help with nested blocks

### ISSUE THREAD

**Issue by a-dpq** [mozilla/nunjucks#1064]
I'm just getting started with Nunjucks and am having trouble getting nested blocks to work. I have a controller block with some code, inside of which the content should be nested. But when I specify the content in my template file, it doesn't appear in the HTML output from Nunjucks. Here are the files (simplified):

components/controller.html.njk:

```
<div id="controller">
    {% block controllerContent %}
    {% endblock %}
</div>
```

layouts/layout.html.njk:

`{% include "components/controller.html.njk" %}`

index.html.njk:

```
{% extends "layouts/layout.html.njk" %}

{% block controllerContent %}
  CONTROLLER CONTENT HERE
{% endblock %}
```

How can I get the content specified in controllerContent to show up inside the controller?

**Comment by ArmorDarks** [comment]
It's because of `include`. I guess when you include partial, it loses some context, thus extending can't extend declared in the included partial block.

If you will do

```jinja
{% extends "components/controller.html.njk" %}

{% block controllerContent %}
  CONTROLLER CONTENT HERE
{% endblock %}
```

it will work.

But for such task it seems that you need `macro` instead of extending. Otherwise you're using extending in a way it wasn't designed to be used...

**Comment by a-dpq** [comment]
Great, the macro solution works for me. Thanks!
