### ISSUE TITLE
Is this possible? --> {% set variable = javascriptFunctionResult() %}

### ISSUE THREAD

**Issue by markrmessmore** [mozilla/nunjucks#1078]
**Full disclosure**: I'm brand new to nunjucks and only a hobbyist programmer/html web designer. Therefore Something may be incredibly straightforward that I'm just not getting.

My question is: as referenced in the title, is it possible to set the value of a nunjucks variable based on the result of a javascript function? Or, must all variable values be hard-coded as they are set? 

Thanks in advance for any assistance.

**Comment by devoidfury** [comment]
Sure you can. Just make sure to pass the function into the template somehow so that it's visible; either with addGlobal or passing it in via the context.

```
> require('nunjucks').renderString('{% set v = fn() %}{{ v }}{{ v }}', {fn: function() { return 12 }})
'1212'
```

**Comment by markrmessmore** [comment]
Thanks for the comment @devoidfury. However due to my n00bishness I still need some explanation.

Since you're using 'require' I'm assuming you're considering nunjucks in a NodeJS environment. I'm not using NodeJS with this current web app therefore require isn't available to me. How would I carry out this same action where I'm really just using HTML and JS (with gulp doing my building)?

Thanks again.

**Comment by devoidfury** [comment]
It'll be the same as however you're using it already, you just need to pass a reference to the function into the template context. You can do this with either the context object, where you're passing in variables already `render(template, context_object)` or with addGlobal `nunjucks_environment.addGlobal(your_fn)`.

I'd have to see your code to give you any better explanation.

**Comment by devoidfury** [comment]
In order to use the templates at all, you have to call `.render` or `.renderString` somewhere. Both of those methods take a second parameter, which is an object to use for template context. Any properties on that object are added to the scope of the template so it can "see" them.

```
> var ctx = {x: 'foo'}
> nunjucks.renderString("hello, {{ x }}", ctx)
'hello, foo'
```

You can pass whatever values you want via that context, including functions.

**Comment by markrmessmore** [comment]
Thanks for the help!

**Comment by RwwL** [comment]
Sorry to comment on a long-dead thread, but I searched for awhile before posting a [new question](https://github.com/mozilla/nunjucks/issues/1243) and finally found this shortly after submitting it... @devoidfury, if the function I want to use is already available in templates as a filter, should it be available to use in `set` commands? For instance, if I already have a filter like this:
```function exclaim = function(content) {
  return content + ' !!!!';
};```
...and I'm able to use it like this `{{ content.title | exclaim }}`
...then should I also be able to do this? `{%  set exclamation = exclaim('Hello') %}`? That seems not to work for me; the entire template fails to render but I don't see an error in the console (this is all happening on the server). I guess I'd have to use `addGlobal` instead of / in addition to `addFilter`?

**Comment by RFlintstone** [comment]
> Sorry to comment on a long-dead thread,
> ...then should I also be able to do this? `{% set exclamation = exclaim('Hello') %}`?

This is basically my question too. The function is available in my template as it does trigger the function although I'm somehow not able to get the output from my function yet. 

```
    {% set movies = api.imdb("value") %}
    {{ movies }} 
    {{ movies | string }} 
    {{ movies | dump }} 
    {# or combination of string and dump #}
```
(This) doesn't work although the API is being triggered. 

```
Console log output: "Something of Value"
```

**Comment by fatchild** [comment]
How did you work around this?
