### ISSUE TITLE
Trying to calculate figure based on 2 dates in Nunjucks

### ISSUE THREAD

**Issue by treacysj** [mozilla/nunjucks#1104]
Hi, I'm trying to set a postfunction in Jira using Nunjucks to calculate the number of days an issue was open based on the created date and closed date of the issue. I have the following:

{{ set issue.fields["Days To Close"] }}
{ issue.fields["Close Date"] - issue.fields[“Created"] | % sum %}
{{ endset }}

But I'm getting an error:
Message:
expected variable end

Is anyone able to help me? Is this even possible to get a numeric figure based on 2 dates? Thanks!

**Comment by ArmorDarks** [comment]
First of all, this question clearly belongs to the Stack Overflow, since it isn't nor a feature proposal, nor a bug report.

Second, your code contains numerous syntax errors, that's why it doesn't work

```jinja
{{ set issue.fields["Days To Close"] }}
```

You can't set properties of objects that way nor in Jinja, nor in Nunjucks. In fact, nor in Jinja, nor in Nunjucks it's possible _at all_ to mutate object properties, except by writing your own filter. Though, I'd recommend not to do this, since such kind of logic doesn't belong to templates.

Also, `set` and `endset` should use `{% %}` tags, not `{{ }}`. `{{ }}` is only for the output.

```jinja
{% set someVariable %}
{ issue.fields["Close Date"] - issue.fields[“Created"] | % sum %}
{% endset %}
```

Here

```jinja
{ issue.fields["Close Date"] - issue.fields[“Created"] | % sum %}
```

Did you mean this?

```jinja
{{ issue.fields["Close Date"] - issue.fields[“Created"] | sum }}
```

You also probably want to group the expression, otherwise `sum` will be applied to `issue.fields[“Created"]` instead of the `issue.fields["Close Date"] - issue.fields[“Created"]`:

```jinja
{{ (issue.fields["Close Date"] - issue.fields[“Created"]) | sum }}
```

**Comment by fdintino** [comment]
Also, if your date variables are not javascript `Date` objects you may not be able to subtract them. I concur with @ArmorDarks that this question would be better suited for stackoverflow.
