### ISSUE TITLE
Nunjucks <-> Jinja2 template converter

### ISSUE THREAD

**Issue by epicfaace** [mozilla/nunjucks#1237]
This might be nice, given [this FAQ item](https://github.com/mozilla/nunjucks/blob/c99154ef3cf18de305944d71da90536f730b326b/docs/faq.md#can-i-use-the-same-templates-between-nunjucks-and-jinja2-what-are-the-differences) says that they are largely compatible. The template converter would only need to perform some minor codemods, and it would make it easier to use the same templates on the frontend and the backend.

**Comment by fdintino** [comment]
I think the goal ought to be to allow jinja2 templates to run unmodified in nunjucks, so long as all filters and custom tags are written for both python and js. That list of unsupported features in the FAQ reflects the current state of the library, but I consider them all bugs.

In short, I agree with your goal for this ticket, but I think the better solution is to fix nunjucks compatibility. It's also the more practicable one, since writing a template converter for these features would be more difficult than just implementing them.
