### ISSUE TITLE
Nunjucks with amcharts problem

### ISSUE THREAD

**Issue by tigredonorte** [mozilla/nunjucks#1244]
I'm trying to initialize an AmCharts data into nunjucks template. I pickup data from req.body and pass it as chartData
```
// server.js
var html = nunjucks.render("template.html", {
    chartData: req.body // chartData: JSON.stringify(req.body)
});

// template.html
am4core.ready(function () {

      chart = am4core.createFromConfig(config, 'chartdiv', am4charts.XYChart);

      // Add data
      chart.data = {{ chartData }};
});

```
I've tried the two approaches above (with and without stringify). But as result the chart data hasn't initialized. There some way to do initialize the template's "char.data" variable?

**Comment by ArmorDarks** [comment]
It seems that `am4core.ready` is async, right? You need to treat it in a [special way then](https://mozilla.github.io/nunjucks/api.html#asynchronous-support).

And you'll need to register it as an async function. Be noted that you'll be forced to use async `addFilter` for it as stupid as it is, since async `addGlobal` [is not implemented yet](https://github.com/mozilla/nunjucks/issues/819).

**Comment by fdintino** [comment]
If you're doing this server-side, you'll need to actually do the render inside `am4core.ready`
