### ISSUE TITLE
Calling API within Nunjucks File

### ISSUE THREAD

**Issue by Abdulsametileri** [mozilla/nunjucks#1259]
I am very newbie in nunjucks.

     {% set projects = [ 
        { 
          id: 3,
          dbaslik: "some data 1",
          ddetay: "some data 1",
          src: "img/someimg1.png"
        },
        { 
          id: 4,
          dbaslik: "some data 2",
          ddetay: "some data 2",
          src: "img/someimg2.png"
        },
        .....
      ] %}
      <div class="owl-one owl-carousel owl-theme">
        {% for project in projects %}
          <div class="item-proje"
              id="project-image-slider-{{proje.id}}"
              data-baslik="{{project.dbaslik}}" 
              data-detay="{{project.ddetay}}" >
            <img src="{{project.src}}"/>
          </div>
        {% endfor %}
      </div>
This is what my own template looks like which is used to populate some projects. But this is just static data as you see. I have to work with real data. So

I need to call specific project api and get projects, assign project variable and populate them using nunjucks? How can I do that?

**Comment by ArmorDarks** [comment]
It depends on your environment. But most likely you need to do API calls outside of the Nunjucks and then pass the result into the context of the template during the rendering.

**Comment by Abdulsametileri** [comment]
Is it possible to show example? I dont think to understand you

**Comment by ArmorDarks** [comment]
Once again, it depends on your environment. Can you explain where and how you're using Nunjucks?

**Comment by Abdulsametileri** [comment]
You can think of my site as an official company website. I have 15 nunjucks files and 25 scss files. Also, have corresponding CSS and HTML files to these files. I currently host my site in GitHub Pages. 

I use nunjucks to easily create dynamic HTML pages. I work on nunjucks file, I serve the file which corresponding HTML file. So, I can easily maintain, I also have an advantage to use programming languages keyword like for, if, etc.

For example, the code above within project.nunjucks file, I easily used a for loop thanks to nunjucks. But it was HTML, ı cannot do that. Because HTML does not support keyword which for, if, etc.

Coming to my questions, Is it possible to populate dynamic projects array, currently I entered static as you have seen above.

in nunjucks file
<script>
   async getProjects() {
        const { response } = await fetch(/api/projects/)
        let projects = response.data
        **// Now, how can I bind projects variable to {% set projects = [...] %}**
   }
</script>

@ArmorDarks

**Comment by ArmorDarks** [comment]
Are you building Nunjucks into static files (html)? Are you using for it Webpack, Gulp, Grunt or anything? If not, you'll need to explain how you're delivering Nunjucks to users (like through Express or something).

**Comment by ArmorDarks** [comment]
Since you're saying they are hosted on Github Pages, I'll assume you're building them into static files with Gulp or something like that.

In such a case, you simply can't bind `projects` to your `response`. The reason is simple — once your template has been built into HTML, it's now just an HTML and nothing more. It doesn't have any Nunjucks variables. What you're declaring in `<scripts>` tag will happen when the user will load the page, and that's AFTER the Nunjucks has been built into the HTML page.

So, by that time `projects` simply no longer exist. So, if it should be a dynamic application, where user loads page and see recently fetched projects, you'll need to use for that a direct DOM manipulation tools (like jQuery), or using some lib which can manipulate dynamically with templates, like old Backbone. Or if a dynamic part is becoming complex, it's better to use for that React or Vue, which are far more suitable for the task.

**Comment by Abdulsametileri** [comment]
> Are you building Nunjucks into static files (html)? Are you using for it Webpack, Gulp, Grunt or anything?

I am using Gulp

**Comment by Abdulsametileri** [comment]
Great explanation. Thank You sir.
