### ISSUE TITLE
Requiring Nunjucks in Jest Leaks Memory

### ISSUE THREAD

**Issue by cyreb7** [mozilla/nunjucks#1271]
We have been trying to identify and fix memory leaks in our tests and have found Nunjucks to be one such culprit. I created a simple example to demonstrate the leak, but the short version is simply calling `require("nunjucks");` leaks about 4MB when running Jest.

Example: https://github.com/cyreb7/nunjucks-memory-leak

Possibly related: https://github.com/mozilla/nunjucks/issues/1021

**Comment by ogonkov** [comment]
How it should look like? For me heap size is 44mb for every run.

node v10.17.0
node-gyp -v v5.0.3
npm 6.11.3

<details>
<pre>
% npm test

> @ test /Users/user/Projects/nunjucks-memory-leak
> node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage t

 PASS  __tests__/test (another copy).js (44 MB heap size)
 PASS  __tests__/test (4th copy).js (44 MB heap size)
 PASS  __tests__/test.js (44 MB heap size)
 PASS  __tests__/test (9th copy).js (44 MB heap size)
 PASS  __tests__/test (3rd copy).js (44 MB heap size)
 PASS  __tests__/test (6th copy).js (44 MB heap size)
 PASS  __tests__/test (5th copy).js (44 MB heap size)
 PASS  __tests__/test (8th copy).js (44 MB heap size)
 PASS  __tests__/test (copy).js (45 MB heap size)
 PASS  __tests__/test (7th copy).js (44 MB heap size)

Test Suites: 10 passed, 10 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        2.484s
Ran all test suites matching /t/i.
</pre>
</details>

If i run `npm ci`, then i see increasing of heap

<details>
<pre>
% npm test            

> @ test /Users/user/Projects/nunjucks-memory-leak
> node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage t

 PASS  __tests__/test (another copy).js (48 MB heap size)
 PASS  __tests__/test (4th copy).js (52 MB heap size)
 PASS  __tests__/test.js (56 MB heap size)
 PASS  __tests__/test (9th copy).js (60 MB heap size)
 PASS  __tests__/test (7th copy).js (64 MB heap size)
 PASS  __tests__/test (8th copy).js (68 MB heap size)
 PASS  __tests__/test (copy).js (72 MB heap size)
 PASS  __tests__/test (6th copy).js (76 MB heap size)
 PASS  __tests__/test (3rd copy).js (80 MB heap size)
 PASS  __tests__/test (5th copy).js (84 MB heap size)

Test Suites: 10 passed, 10 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        3.511s
Ran all test suites matching /t/i.
</pre>
</details>

It also has errors on installation

<details>
<pre>
% npm ci

> fsevents@1.2.11 install /Users/user/Projects/nunjucks-memory-leak/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Projects/nunjucks-memory-leak/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
added 471 packages in 8.921s
</pre>
</details>

Looks like leak is caused by some third-party dependency.

**Comment by cyreb7** [comment]
@ogonkov 

node v12.16.1
node-gyp v3.8.0
npm 6.14.4

I get the same issue with `npm ci` or `npm install`:

<details>
<pre>
> @ test /mnt/d/Bryce/Documents/nunjucks-memory-leak
> node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage t

 PASS  __tests__/test.js (38 MB heap size)
 PASS  __tests__/test (6th copy).js (42 MB heap size)
 PASS  __tests__/test (another copy).js (46 MB heap size)
 PASS  __tests__/test (5th copy).js (50 MB heap size)
 PASS  __tests__/test (9th copy).js (53 MB heap size)
 PASS  __tests__/test (7th copy).js (57 MB heap size)
 PASS  __tests__/test (4th copy).js (61 MB heap size)
 PASS  __tests__/test (3rd copy).js (65 MB heap size)
 PASS  __tests__/test (copy).js (68 MB heap size)
 PASS  __tests__/test (8th copy).js (72 MB heap size)
</pre>
</details>

But trying `npm update` I found it seems to be fixed in [Nunjucks v3.2.1](https://github.com/mozilla/nunjucks/releases/tag/v3.2.1)! I assume judging by your error and the Nunjucks update that `chokidar` was causing the issue.
