### ISSUE TITLE
Page Not fully Rendered in browser

### ISSUE THREAD

**Issue by Previesam** [mozilla/nunjucks#1290]
Well done All,

I have this issue, installed nunjucks, added html to my index.njk file and did all the necessary express setup, the page renders and everything is supposed to be fine except that the page loads but only the part of the page that is visible displays when I scroll down on the page I find spaces for content that have been loaded but are not displayed.

I have tried loading the html in static mode without nunjucks and it works fine the element animates in as I scroll down on the pages, which is not the case when I was using the template.

I also noticed that in the template mode, when I start resizing the page manually, the elements that were not showing before will start showing, but when I reload the page they will disappear again

Please what could be the issue

**Comment by ogonkov** [comment]
If elements is showing after page resize, that mean that template render html correctly, and problem is not in nunjucks.

**Comment by Previesam** [comment]
Thank you for the response, But the problem is certainly with nunjucks
because I was not able to reproduce the problem with other template engines
like Vash. The problem here is that every other template engine that uses
syntax similar to that of liquid has the same issue. e.g liquidjs and liquid

**Comment by ogonkov** [comment]
Can you create repo to demonstrate problem?

**Comment by fdintino** [comment]
I think there isn't enough information here to help troubleshoot, let alone to determine whether this is a bug in nunjucks, a problem with how it's being called from your application, or something unrelated.

In order to help clear the ticket backlog, I'm going through and closing all github issues that don't have enough information to be actionable. If you can find time to put together a minimal example demonstrating the problem, please reopen this issue with that information.
