### ISSUE TITLE
Will nunjucks support stream

### ISSUE THREAD

**Issue by popomore** [mozilla/nunjucks#180]
Like dustjs

https://github.com/linkedin/dustjs/blob/master/docs/api.md#the-streaming-interface

**Comment by jakearchibald** [comment]
With streaming coming to the client & service worker, this may be worth revisiting?https://jakearchibald.com/2016/streams-ftw/#creating-one-stream-from-multiple-sources-to-supercharge-page-render-times

Also, dustjs was of real benefit when I built https://wiki-offline.jakearchibald.com/ (explaination https://www.youtube.com/watch?v=d5_6yHixpsQ&feature=youtu.be&t=4m22s), since some of my data was slower to arrive.

Unfortunately I have nothing nice to say about dustjs's syntax.

**Comment by Snugug** [comment]
I'd like to see this revisited as well

**Comment by Hurtak** [comment]
Any update on this or is the maintainers stance still the same?

**Comment by vecmezoni** [comment]
No updates, i think we should focus on compatibility with jinja rather than implementing new APIs for now.

**Comment by joakimstai** [comment]
Marko is another streaming templating engine, and [its benchmarks](http://markojs.com/docs/marko/what-is-new-marko-v3/#improved-performance) are interesting.

Streaming is probably not that often required, but there are use cases where it can really improve performance. Like static site generators rendering hundreds/thousands of files, server-side rendering, and even client-side rendering like @jakearchibald demonstrated. I think it's worth looking into, at least eventually.
