### ISSUE TITLE
Filters not allowing multiple function calls

### ISSUE THREAD

**Issue by garygreen** [mozilla/nunjucks#247]
Take for instance you have a `moment` filter which filters the value into a Moment date object:

	// moment date filter
	env.addFilter('moment', function(dateString, format) {
		var date = moment(dateString);
		return format === undefined ? date : date.format(format);
	});

Now in your template you do something like;

	{{ '2014-01-01'|moment('DD/MM/YYY') }} # Outputs: 01/01/2014, correct.

If you want to access any of the Moment objects methods:

	{{ '2014-01-01'|moment().add('days', 15).format('DD/MM/YYYY') }} # Outputs: 01/01/2014, incorrect.

This is because nunjucks seems to only use the last `.format()` and ignores all the preceding function calls -- the above compiled to:

	function root(env, context, frame, runtime, cb) {
	    var lineno = null,
	        colno = null,
	        output = "";
	    try {
	        output += runtime.suppressValue(env.getFilter("date").call(context, "2014-01-01", "DD/MM/YYYY"), env.autoesc), cb(null, output)
	    } catch (e) {
	        cb(runtime.handleError(e, lineno, colno))
	    }
	}

**Comment by jlongster** [comment]
Not sure exactly what to do here. Filters are kind of weird; they are basically just a weird syntax for calling functions. I'd rather not overload filters and make them too powerful, but I personally am starting to favor just calling functions anyway. As you mentioned, calling functions and passing the argument manually works.

Closing for now, feel free to re-open if you have any ideas!

**Comment by ArmorDarks** [comment]
My issue was referencing to same problem, so it probably have to be closed too as duplicate https://github.com/mozilla/nunjucks/issues/411

Well, I had strange feeling about filters too, since defined in Globals functions can do everything filter can and even more. The only difference is syntax — in case of filter you have to type a bit less, a bit nicer code.

However, personally I think that filters should support calls too, to be unified with Globals. Besides, it's logical to expect function to support calls to it's method (since filter is basically a function). But it will be, on other hand, unsupported in Jinja. Maybe it worth open ticket on Jinja's tracker about implementing similar feature.

**Comment by jlongster** [comment]
I'm definitely open to improving the coordination between filters & function calls. It's just a bit weird because I think filters want you to do `"value" | foo | bar(3) | baz`, but you almost always want to use the normal function syntax (especially since you can access native JS methods).

I don't think I have time to seriously work on this, but I would accept a PR that improves the filter parsing.
