### ISSUE TITLE
Precompile file(s) with dependencies

### ISSUE THREAD

**Issue by at0g** [mozilla/nunjucks#362]
Is it possible to bundle dependencies (extends, import etc) when precompiling individual templates via the API methods?

For example:

parent.nunj
```
{% block foo %}parent{% endblock %}
```

child.nunj
```
{% extends 'parent.nunj' %}
{% block foo %}{{ super() }} -> child{% endblock %}
```

my_compiler.js
```
// When tpl is called, an XHR request is made for parent.nunj
// If the XHR is not resolved, then a runtime error is triggered
var tpl = nunjucks.precompile('child.nunj');
```

If I precompile all of the templates, or add all of the files explicitly, then it's no problem.

Is this behaviour by design?

**Comment by jlongster** [comment]
It is somewhat by design. More like: we took the easy approach. We don't walk dependency trees. 99% of the time you just want to lump in specific directories.

I understand that it's primitive though. Note that extends/include can take dynamic variables, so the dependency tree is not deterministic. You could build a tool that walks the static dependency tree though and automatically passes these files to the precompile API, that would be neat.
