### ISSUE TITLE
undefined variables vs undefined functions

### ISSUE THREAD

**Issue by jmls** [mozilla/nunjucks#368]
if you don't have a variable defined, the output is blank

Hello{{ foo.bar }}World

results in HelloWorld

however, if you call an undefined function

Hello{{ foo() }}World

then nunjucks borks with the error 

Template render error: Error: Unable to call `foo`, which is undefined or falsey

is there an option to return "" in the case of a missing function, as the missing variable does ?

thanks

**Comment by jlongster** [comment]
Not really, this gets into very ambiguous territory about where we suppress non-string types. Right now it's pretty simple: anything null or undefined going out to the world is not shown.

It's quite different to ask for a mechanism that basically suppresses all errors. It's too complicated to figure out what to suppress and not and it's ripe for suppressing an error when the user really should be handling it. Closing for now unless someone wants to convince me otherwise.

**Comment by pedrovagner** [comment]
What about implement a feature called <b>safe navigation</b>: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#safe-navigation-operator
