### ISSUE TITLE
1.3.4 browser files not re-generated

### ISSUE THREAD

**Issue by arthurjamain** [mozilla/nunjucks#422]
Hey there,

Not sure this is the proper place to ask/report this ; sorry if it's not !

I've been waiting for a few fixes in the 1.3.4 release that just got out two days ago. However, it seems that the browser/ files (which I mainly use) were not re-built and still use the 1.3.3 code.

Is there a reason for this ? Should I try and build it myself, or should I wait for an official build ?

Thanks !

**Comment by popomore** [comment]
@jlongster  Seem always happen when publish,  we can add prepublish scripts for browserfiles.

**Comment by jlongster** [comment]
Prepublish would not help, the browser JS files are not downloaded from npm. They are committed in git and pushed out to the docs.

You're right we need to make sure we recompile them though.

@arthurjamain I don't know what you are waiting for, there is literally no difference between 1.3.3 and 1.3.4. The only thing that happened there was we don't push a bunch of extra stuff (tests) to npm. The browser file doesn't have any additional fixes.

Still, you're right, it's bad that I didn't recompile them. There's already a bunch of stuff on master and I'm going to make another release soon, so let's just wait for that. There really isn't anything new in 1.3.4.

**Comment by popomore** [comment]
Prepublish can do everything before publish, you can generate the browser file and commit it.

**Comment by arthurjamain** [comment]
Thanks for the feedback & clarifications.

@jlongster Yeah, it seems I've misread the changelog — my bad. It's still good to know where to stand on the issue tho. Thanks !

**Comment by jlongster** [comment]
@popomore true but there are more things that need to happen (copy to docs, publish docs) and I'm weary of hooking that into the prepublish for some reason. We should automate it somehow though, and maybe prepublish is it, I just want to be very careful about tools that automatically create git commits, push, etc. and make very clear that what you're about to do does all that. (My gut prefers an explicit deployment step which does `npm publish` at the end rather than the other way around).

I'll think about it a little more though.

**Comment by jlongster** [comment]
Closing for now since there's no difference between the 1.3.3 and 1.3.4 files. If you really want them, check out and just run `npm run browserfiles`. I'll automate the process better soon.
