### ISSUE TITLE
Process hangs due to open handles

### ISSUE THREAD

**Issue by michel-kraemer** [mozilla/nunjucks#429]
I'm running nunjucks in a gulp build script. Everything works OK, but the process does not exit. I used `process._getActiveHandles()` to debug the problem and noticed that nunjucks keeps handles open. They are created in this line: https://github.com/mozilla/nunjucks/blob/master/src/node-loaders.js#L42

I understand `FSWatcher` from the `chokidar` package has a `close()` method and I wonder if this method should be called to free all resources?

Thanks,
Michel

**Comment by jlongster** [comment]
You can just turn watching off: `nunjucks.configure({ watch: false })`. Note that we are about to release 2.0 and watching will be turned off by default.

**Comment by michel-kraemer** [comment]
That's good to know. Thanks.

**Comment by chocolateboy** [comment]
In case anyone else has the same problem, this is also causing nunjucks + [render-cli](https://github.com/debrouwere/render) (which uses [consolidate](https://github.com/tj/consolidate.js)) to hang.

(In my case, an upgrade to version 2.0.0 may not be practical since it [enables autoescaping by default](https://github.com/tj/consolidate.js/issues/170) (I'm using it to generate code), and consolidate doesn't provide a [sensible way to pass options to the template engine](https://github.com/tj/consolidate.js/issues/170) so there's no generic way to override either of these options).

**Comment by michel-kraemer** [comment]
@chocolateboy Indeed. I had the same problem so I removed consolidate.js from my tool chain in order to be able to use nunjucks directly. Not the best way, but it's working.
