### ISSUE TITLE
Is {% trans %} available?

### ISSUE THREAD

**Issue by xethorn** [mozilla/nunjucks#442]
Quick question: I've been looking in different places, and it doesn't look like `{% trans %}` is available in nunjucks (found one extension - nunjucks-i18n, but it's not really supporting much). What's the best way today to make translation work in nunjucks (especially for plurals.)?

**Comment by ArmorDarks** [comment]
So far there is no good way, unfortunately.

You must use nunjucks-i18n, or some external, let's say, Grunt task for replacing parts of text, or write your own extension/filter/global function.

I don't think that nunjucks out of box will ever support i18n, since it's merely impossible to support all popular nowadays i18n methods — they are way too different. Besides, in the end of all, it's not templating engine work.

**Comment by jlongster** [comment]
Agreed, this is definitely something that should be in userland.
