### ISSUE TITLE
Calling js function with parameter?

### ISSUE THREAD

**Issue by Rexota** [mozilla/nunjucks#445]
Hey

Can't we call a js function with parameter?

    {% set item_id_for_like = 'likeContent('+item.content_id+')' if user.isLoggedIn else 'showRegisterOrLoginDialog()' %}

showRegisterOrLoginDialog() working but likeContent(x) giving ILLEGAL TOKEN error.

These functions are front-end functions.
Where is my fault? Thanks.

**Comment by ArmorDarks** [comment]
You definately *can* do that.

Regarding your code — shouldn't it be something like that?

``` twig
{% set item_id_for_like = likeContent(item.content_id) if user.isLoggedIn else showRegisterOrLoginDialog() %}
```

Or what are you trying to achieve?

**Comment by ArmorDarks** [comment]
Ah, now I've probably get it. You want to output `likeContent(*yourVarHere*)` inside your html, so that browser's JavaScript could execute it?

I've tested your code with my own variables and it works perfectly fine in my environment. No errors, expected output `likeContent(*yourVarHere*)` after interpolation.

I guess your template has typo or error somewhere else, or maybe provided variables somehow messing up code.

**Comment by Rexota** [comment]
I gave up and used jquery to solve that question. Thanks.

**Comment by jlongster** [comment]
Looks like you wanted to execute JS in different environments (you can't literally eval JS in nunjucks).

**Comment by Rexota** [comment]
This works:

    {% 'test()' if __thing__ else 'blaBla()' %}

But this doesn't work:
    {% 'test()' if __thing__ else 'blaBla(obj.fromServerRender)' %}
