### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by jlongster** [mozilla/nunjucks#500]
I'm looking for someone to take over cutting releases. That's pretty much all I do now; the rest of this project is very community-driven. But having everyone blocked on me isn't really scalable anymore, as I don't have any projects using nunjucks these days.

There's a bunch of good stuff being built on nunjucks, and I think it's in good shape and can only get better with more contributions. I think all projects eventually become owned by the contributors.

I'm fine helping triaging issues and still helping people when they get stuck in the code! But I just feel too much guilt right now when neglecting it. @carljm you may be the most likely one to take over releases, what do you think? or @SamyPesse, who also have a vested interest in the project. or both.

**Comment by carljm** [comment]
Hi James. Even if you haven't been very active recently, I don't think it's really true that all you do is releases; just in the past couple days you've merged a number of PRs and commented on quite a few other issues. While the community has been very active and helpful, I think it's important to recognize that there is a leadership role needed that goes beyond just cutting releases; someone who makes the final call on design decisions and merges.

In theory, I'd be quite happy to take over this role. I am actively using nunjucks, and I'd like to help. In practice, I'm concerned that my OSS bandwidth is already over-committed, and I'd just become another inattentive project owner :-/ I think I would especially find it difficult to find time to review or merge contributions that didn't correspond directly to my own needs, which are quite specific (as we've discussed in other tickets) -- I have no use for anything that isn't strictly Jinja-compatible.

So I guess the takeaway is this: if there's no better candidate (i.e. the above paragraph doesn't scare anyone else into volunteering!), I'll do it (with help from @jgerigmeyer on the webpack/releasing side of things, since I'm less familiar with the JS ecosystem). Just want the caveats to be clear in advance :-)

**Comment by carljm** [comment]
(I'm also happy to work on it with someone(s) else. A team is good.)

**Comment by jlongster** [comment]
@carljm While it's true I have the context to reply to issues and PRs (because I wrote most of the code), I'm mostly riding on ideas from when I wrote the code. I don't have any specific vision or goals, so it wouldn't be hard to express the guidelines that I go by when responding to issues:

* Prefer to keep templates (including filters, extensions, etc) more strict rather than less. This means that errors should throw, and the user should see plainly when something's wrong. (example: passing a number into the `title` filter). This means things like `copySafeness` that deal with strings should assume that their arguments are strings (we could even put `assert`s there).
* Always allow precompilation
* Avoid features that incur a big runtime cost

That's been my philosophy so far, and I respond with that in mind. I generally merge stuff that doesn't violate the above, even if I don't fully understand the implementation. I don't really know the code anymore. Take #489, I tried to fix it but at this point I can't remember enough about the parser/compiler APIs to come up with the proper fix.

If you'd like to at least just take over looking at PRs every now and then and cutting releases when some changes have been made, that would be great. We can make it clear that you also aren't going to drive a lot of development. If people want some feature, they are just going to have to implement it themselves at this point and be willing to wait until it can be looked at. People can't expect every OSS project to be moving fast.

I need at least one other person looking at PRs, making final decisions, and cutting PRs. I can't afford the mental burden of looking at this repo much anymore, there's just too many things going on!

**Comment by carljm** [comment]
> I need at least one other person looking at PRs, making final decisions, and cutting PRs. I can't afford the mental burden of looking at this repo much anymore, there's just too many things going on!

I've been there, and I totally understand, especially if you aren't even using it anymore!

I didn't at all mean to be suggesting above that _you_ should continue to be the decision-maker if you no longer want to be. I was just clarifying that there is a bit more that needs to be done (by someone) than just "cutting releases," and trying to be clear about my (time and interest) limitations in taking on that role.

I'll give it a try and we'll see how it goes!

**Comment by SamyPesse** [comment]
@jlongster I think both @AaronO and myself can help you and @carljm maintain `nunjucks` (e.g Write fixes, merge PRs, manage releases, ...) since we use it in different projets ([GitBook](https://github.com/GitbookIO/gitbook), [GitBook.com](https://www.gitbook.com)).

But as @carljm, we already have other full-time projects that take up a lot of our time, but as a team I think we can make this work.

If you and @carljm are okay with that, you can grant us collaborator access (GitHub and NPM).

**Comment by carljm** [comment]
Great! Works for me :+1:

**Comment by jlongster** [comment]
Sounds great to me too! While some people probably would like there to be a very active development team, I think it's perfectly fine if a project is alive but stable, with relatively few changes. Not every project needs to take over the world.

I'll look at what I need to do to grant any access. Some people already have commit access here, so I guess it's mainly NPM.

Also, not sure you've seen this, but here is how I do releases: https://github.com/jlongster/nunjucks/blob/master/MAINTENANCE.md. @carljm is improving changelogs, and I'm sure there are better ways to automate the process, but at least it's documented.

**Comment by carljm** [comment]
I hadn't seen that - thanks for documenting all that!

**Comment by jlongster** [comment]
@carljm funnily, there's steps in there for updating CHANGELOG.md :p Haven't updated it for a while.

Also, uh... I think I accidentally revoked myself as a contributor. @carljm you should be an admin now, can you add me back as an admin?

**Comment by carljm** [comment]
Ha! I guess your subconscious desire to rid yourself of responsibility for nunjucks is strong ;-) Added you back as an admin.

**Comment by jlongster** [comment]
Haha. @carljm and @SamyPesse can you give me your npm usernames? I'll add you as owners to the nunjucks repo.

**Comment by carljm** [comment]
@jlongster I'm `carljm` on npm. And everywhere else.

**Comment by SamyPesse** [comment]
@jlongster I'm `samypesse` on npm :)

**Comment by jlongster** [comment]
Added! Thanks a lot all :)

**Comment by boutell** [comment]
Thanks to all who stepped up here.
