### ISSUE TITLE
nunjucks.render always uses config from last call to nunjucks.configure

### ISSUE THREAD

**Issue by andrewchernow** [mozilla/nunjucks#531]
I am using v2.1.0 from the browser only.

`nunjucks.render()` is a little bit dangerous. Since `nunjucks.configure` caches the `Environment` it creates, a second call to `configure` will cause an innocent victim's `Environment` to be overwritten; if they choose to use `nunjucks.render` rather than `Environment.render`. 

I couldn't find this documented anywhere. I think it should be (warning) or `nunjucks.render` should require an `Environment` argument.

I'm guessing it is coded this way since the most common use case is to create just one `Environment` or not create one at all and just start calling `nunjucks.render`.

**Comment by carljm** [comment]
Yeah. I guess it was done this way so that you could just call `nunjucks.configure` (ignoring the returned environment) and later `nunjucks.render`, and have it respect the configuration you'd set. But I agree this is a bunch of implicit global state that is problematic.

In the short term we should just document clearly that `nunjucks.render` always uses the configuration from the last call to `nunjucks.configure`, so you probably don't want to ever use it if you are creating more than one environment.

In the longer run, I think the best/simplest option might be just to deprecate `nunjucks.render` entirely, and require always creating an environment and calling `env.render`.

**Comment by andrewchernow** [comment]
Unless I am missing something, can't you just call `nunjucks.render` without configure, which would use all of the default options? I am only using this from the browser so I am not sure what express would do.

I agree that deprecating `nunjucks.render` is probably the way to go.

**Comment by carljm** [comment]
@andrewchernow 

> Unless I am missing something, can't you just call nunjucks.render without configure, which would use all of the default options?

Yes, you can, and obviously that's one use case for `nunjucks.render`. What I was trying to explain above is why there is interaction between `nunjucks.configure` and `nunjucks.render` at all (instead of `nunjucks.render` just caching its own default environment). The latter was my first thought of how to fix this (remove the caching from `nunjucks.configure` and just have `nunjucks.render` cache its own environment), but then I realized that would break the use case I described above.

> Absolutely terrific engine BTW. nice job.

Credit to @jlongster for that - I just help with maintenance.

**Comment by carljm** [comment]
Added a documentation note in c6eee65

**Comment by carljm** [comment]
I'm going to close this issue. I've added a documentation note which will hopefully be effective in warning people of this behavior. I still feel like all else equal I probably wouldn't choose to provide `nunjucks.render` at all, but all else isn't equal -- the API is out there and people may be depending on it. I don't think it's worth removing it.

**Comment by andrewchernow** [comment]
The only additional (safe) step is to deprecate nunjucks.render, but I think the doc warning will do the trick.
