### ISSUE TITLE
Render external templates from S3

### ISSUE THREAD

**Issue by ribase** [mozilla/nunjucks#545]
Hi
at the moment, if i try to understand the manual, it is impossible to have absolute paths like 
- "http://s3-eu-west-1.amazonaws.com/my-fancy-bucket/my-fancy-template-folder/template.html"

Everything ist working fine on local machine, but on the server i need them s3 links.
Regards
Ribase

**Comment by carljm** [comment]
True, the WebLoader docs say it is limited to same-domain base URLs. I assume this is due to browser cross-origin rules, though I haven't looked into it. It seems like that could probably be worked around with appropriate CORS headers on your S3 bucket. It may be that WebLoader already works fine if you set the appropriate CORS headers. If not, you can look at WebLoader and write your own loader that works with remote URLs.

All that said, if you care at all about performance you really must precompile your templates for production use, so I don't really see any good use case for supporting this out of the box.

**Comment by ribase** [comment]
Hey!
Many thanks, good advice, works fine.

Regards
