### ISSUE TITLE
Include template with macros inside dont work

### ISSUE THREAD

**Issue by Danieler** [mozilla/nunjucks#558]
If i try to call a macro included inside other file it dont work.
Example:

components.twig:

          {% macro one(param) %}
          ...
          {% endmacro %}

          {% macro two(param) %}
           ...
          {% endmacro %}

test.twig:

          {% import "components.twig" as components %}

page.twig:

         {% include "test.twig" %}
           {{ components.one(param) }}
           {{ components.two(param) }}

page twig cant access macros

**Comment by carljm** [comment]
This is working as designed (and Jinja works the same way). An include doesn't pull in defined names from the other template into the current template's namespace. This may seem convenient, but just makes the templates harder to read, because you never know where a given name may have come from. If you want access to your component macros in `page.twig`, import them there.
