### ISSUE TITLE
default filter is no longer a default filter

### ISSUE THREAD

**Issue by andrewchernow** [mozilla/nunjucks#569]
Is there any chance of reverting the default behavior of the default filter back to pre-2.0 behavior? The new behavior is unexpected and IMHO a default filter should not be looking at the kind of false value supplied. The new behavior is much more like SQL IFNULL, which specifically checks for a NULL value rather than falsy. That is what this new behavior is doing, except it is looking for undefined values.  What was this change based on: user requests, internal decision, etc..? Is that documented somewhere?

I think it would be cleaner and clearer to add another filter called IFUNDEF and revert the default filter to pre-2.0 behavior.

In most cases, I need pre-2.0 behavior so using the built-in version now requires me to pass a boolean argument to a default filter; which is kind of strange.  For now, I have overridden it with a custom version using addFilter.

**Comment by carljm** [comment]
I don't think there is a chance of reverting back to the previous behavior. The decision was based on two factors:

1) Jinja2 compatibility. The new behavior matches the behavior of Jinja2, and nunjucks aims for Jinja2 compatibility.

2) `{{ value|default('empty') }}` under the old behavior is entirely equivelent to `{{ value or 'empty' }}`, which is easier to type and easier to read. Thus the old behavior is just a redundant spelling of something that is better spelled otherwise. Whereas the new behavior is both useful and something you can't easily get without the filter.

If "in most cases you need pre-2.0 behavior" I strongly recommend simply using `or` instead of passing the boolean argument to the `default` filter. I'd welcome a PR to recommend that in the documentation, too.

**Comment by carljm** [comment]
(The title of this issue is inaccurate. The current behavior of the default filter is a default filter -- it is a default for values which are not present. It is not a default for all falsy values. Both of those behaviors are "default filters," and there is no inherent reason to assume that "default" means one over the other, other than being accustomed to the previous behavior.)

**Comment by andrewchernow** [comment]
Understood. That makes sense. Yes, using `or` is better than passing the boolean. It will also work with both pre and post 2.0 deployments. For me, it is still more readable to do:

`value | ifundef('default')` vs. `value | default('default')`

I do have cases where I want to check undefined only. `default` makes me think "if falsy, use fallback value"; maybe because I've been using Twig for years. 

What is interesting is that I tend to need `coalesce` quite a bit, but have yet to see any template engine implement it.

**Comment by carljm** [comment]
Yeah, I agree that `default` isn't as clear as `ifundef`, but I don't feel it's worth breaking Jinja2 compatibility (and backward compatibility), or providing the same filter under two different names, over.

**Comment by andrewchernow** [comment]
No, it is not worth it. It is also trivial to add your filter to add behavior or aliases.
