### ISSUE TITLE
Transform context passed to template before rendering

### ISSUE THREAD

**Issue by rightaway** [mozilla/nunjucks#579]
I'm using nunjucks with express and can't see how to transform the context that's passed to the template prior to rendering. For example, if an object is passed to the template as context, there should be a way to change that object before the template sees it. Or adding a common object to the context.

**Comment by carljm** [comment]
I think this is out of scope for the (very simplistic) Express integration built-in to Nunjucks. 
Frankly, I think it might be best to remove the Express integration altogether and just document how to do it yourself, which would allow more customization of the integration.

I recommend that you take a look at the `express` function in `src/environment.js` to see what Nunjucks actually does with your express app when you pass it in to `configure`. If you do roughly the same in your own code instead of passing your express app to Nunjucks, you can easily make all the customizations you mention.

**Comment by rightaway** [comment]
In the file you referred me to there's

```
        NunjucksView.prototype.render = function(opts, cb) {
          env.render(this.name, opts, cb);
        };
```

You mentioned
> If you do roughly the same in your own code instead of passing your express app to Nunjucks, you can easily make all the customizations you mention.

But I don't see access to `req` and `res` objects, so I'm not sure where to make these customizations.

**Comment by carljm** [comment]
Sorry, I don't actually know enough about express to answer that question -- I just assumed that if you handle the integration yourself it should be possible to do whatever you want. This is really a question about express, not a question about nunjucks; nunjucks exposes a simple rendering API; getting the context for that render populated is outside of nunjucks' scope.

I do see in reading http://expressjs.com/guide/using-template-engines.html that it seems nunjucks' express integration isn't even following express' documented template-engine-integration protocol, which would appear to strengthen the argument for removing it.
