### ISSUE TITLE
can I write more like html ?  {%myTag attr1=a, attr2=b %}  vs {%myTag attr1=a  attr2=b %}

### ISSUE THREAD

**Issue by atian25** [mozilla/nunjucks#599]
split attrs with space , not comma

**Comment by carljm** [comment]
The custom tag API exposes the lexing and parsing to your custom tag directly, so you can do whatever you want in a custom tag.

**Comment by atian25** [comment]
it will throw error missing comma

**Comment by carljm** [comment]
Only if you're using a higher-level parsing method like `parseSignature`, which expects commas between args. But you don't have to use that, you can do whatever you want to parse your args. (Of course, the lower-level parser details aren't documented, so that will require diving into the parser code).

**Comment by atian25** [comment]
@carljm thanks, using lexer is too hard for me.
wonder if there can be a config to tell `parseSignature` both support comma and space

**Comment by carljm** [comment]
No, I don't think so. The nunjucks way is to separate arguments with a comma. If you want to do something different, that's fine, but there's no reason to have that in nunjucks.
