### ISSUE TITLE
What about incremental-dom?

### ISSUE THREAD

**Issue by gig177** [mozilla/nunjucks#633]
Do you have any idea how to precompile nunjucks to [incremental-dom](/google/incremental-dom)? How can I use parser api? Is it possible at this moment?

**Comment by ricordisamoa** [comment]
I am not sure whether Nunjucks, as a general templating engine, has any knowledge of HTML at all.

**Comment by carljm** [comment]
Nunjucks doesn't have any knowledge of HTML, and no plans to add any. I'm sure you could write a template engine that precompiles to incremental-dom, and you might be able to re-use some of nunjucks' parser (though I think you'd need more than that, since you'd need a parser that also parses HTML tags), but you'd be writing an entirely new compiler, I think. So the result would not be nunjucks in any recognizable sense, I don't think.

**Comment by gig177** [comment]
Thanks for your thoughts.
