### ISSUE TITLE
Error when trying to extend Nunjucks template

### ISSUE THREAD

**Issue by LandonSchropp** [mozilla/nunjucks#642]
I'm setting up a Gulpfile with `gulp-nunjucks`, and I'm running into an issue when trying to use `extends`.

`source/templates/layout.html`:

```
<!doctype html>
<html lang="en">
  <head>
    <title>Example</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

```

`source/templates/index.html`:

```
{% extends './layout.html' %}

{% block content %}
  <p>Hello!</p>
{% endblock %}
```

Whenever I try to compile my file, I get this error:

```
Template render error: (unknown path)
Error: template not found: ./layout.html
```

As far as I can tell, everything should be working. [Here's](https://github.com/LandonSchropp/nunjucks_example) a link to the full repo. Thanks in advance!

**Comment by carljm** [comment]
Normally with `extend` (and `include`) you don't provide paths relative to the current file, but relative to your template root path (configured when you call `nunjucks.configure`, or alternately when you instantiate e.g. a `FileSystemLoader` and then pass it to `nunjucks.configure`. And normally the template paths you pass to extend/include are bare relative paths (e.g. `layout.html` not `./layout.html`, or `foo/layout.html` not `./foo/layout.html`).

I'm not sure how `gulp-nunjucks` configures nunjucks, and don't have time to investigate right now, but hopefully the above puts you on the right path to figuring out what's going on.

Closing the issue for now; we can re-open if you investigate and are able to confirm a specific bug in nunjucks here.

**Comment by coldice** [comment]
I had a similar problem, adding a comment here because this seems to be the only proper resource returned by google when looking for this. I tried to use the cli to precompile some files (`nunjucks-precompile`). I got the same error, which is basically caused if the file can not be found. In precompile.js, line 84 `if (pathStats.isFile())` will throw if the file is not found. I suggest this should be checked and a proper error message should be returned.

Which took me an hour to figure out though is this: By default, only files ending with `.html` or `.jinja` will be picked up. As my files were names `.njk`, the script just ignored them all.
The helptext says:
```
  -i, --include  Include a file or folder which match the regex but would
     otherwise be excluded. You can use this flag multiple times
     [string] [Standard: ["\\.html$","\\.jinja$"]]
```

For me, it looked optional, only by looking into the code I understood that otherwise it is limited to this default set. I would strongly recommend to add a note about this to the API / precompilation section.
