### ISSUE TITLE
Export Context class

### ISSUE THREAD

**Issue by zbyte64** [mozilla/nunjucks#674]
I have a need for rendering just a select set of blocks as part of a live updating/rerender. I am doing this by compiling a Template and accessing the blocks property directly. As part of that I need to pass in a Context object but it is not exported anywhere. For now I just copied and pasted the implementation.

Could environment.js also export Context?

**Comment by carljm** [comment]
The preferred way to do this is by turning the contents of those blocks into includes or macros, and just rendering those, rather than rendering the whole template and poking into undocumented internal API to pull out the blocks.

I'm kind of hesitant to export the Context object. In the immediate sense it wouldn't cause any harm, but I'm not willing to adopt any backwards-compat guarantees whatsoever (even in bugfix point releases) regarding the behavior of the Context object. And if we aren't adopting back-compat guarantees, it sort of seems like it shouldn't be exported.

**Comment by zbyte64** [comment]
Unfortunately for this particular case we do not have intimate knowledge of the template itself to know what includes it would be using. What we are doing is allowing a user to edit the context of an arbitrary page and view the page as it changes.  So we do want to render the whole template and then only render the top level blocks as the user types. Now that I have it working, I am pretty happy with the results :) But I understand this is atypical usage.

C'est la vie

**Comment by carljm** [comment]
That is a neat use-case (though I'm not entirely sure I understand why you can't just re-render everything in that case). Not totally closed to reconsidering, especially if we get multiple requests for this kind of support.

**Comment by zbyte64** [comment]
I don't really want to rerender the entire page (it is stuffed in an iframe, all this is client side magic) for every edit. That would cause the css and javascript to reload so updating content wouldn't look very smooth. I doubt anyone else is crazy enough to do this :-p
