### ISSUE TITLE
set block only evaluates to a string

### ISSUE THREAD

**Issue by roobottom** [mozilla/nunjucks#708]
As nunjucks now supports using [set as a block](https://mozilla.github.io/nunjucks/templating.html#set) I wanted to do something like this:

```
    {% set navigationItems %}
      {% for item in items %}
        { name: item.name, url: item.url }{% if not loop.last %},{% endif %}
      {% endif %}
    {% endset %}
````

Then call this variable as the input object on another macro, like so:

```
    {{ navigation(items=[navigationItems]) }}
```

However, `navigationItems` is evaluated as a string, not an array-literal. Is this intended behavior?

Thanks.

**Comment by legutierr** [comment]
This is definitely intended behavior.  When evaluated, every nunjucks template renders to a string, and the "partial" template that is rendered inside of a set block is no exception.

If you want to convert that string into a dictionary, you could write your own function or filter that decodes json.  But you would have to make a couple of other changes, too, and you would have to know and trust your data (or otherwise escape it):

     {% set navigationItems %}
       {% for item in items %}
         { "name": "{{ item.name }}", "url": "{{ item.url }}" }{% if not loop.last %},{% endif %}
       {% endif %}
    {% endset %}
    {{ navigation(items=[navigationItems|loadjson]) }}

**Comment by roobottom** [comment]
Thanks @legutierr
