### ISSUE TITLE
Nunjucks implementation of built-in `round` filter does not match jinja documentation

### ISSUE THREAD

**Issue by justinsthomas** [mozilla/nunjucks#712]
The Nunjucks docs for built-in filters (https://mozilla.github.io/nunjucks/templating.html#builtin-filters) point to the Jinja2 docs (`round`, for example: http://jinja.pocoo.org/docs/dev/templates/#round).

The issue I'm encountering is as follows:

`{{ 3.4545 | round }}` returns `3.0` with jinja
`{{ 3.4545 | round }}` returns `3` with nunjucks

According to the jinja docs, I should have to append the `int` filter (`{{ 3.4545 | round | int }}`) to return `3`, but this is not the case. This should be able to be remedied by adding `.toFixed(1)` to the returned value of the `round` filter; pull request coming soon.

**Comment by legutierr** [comment]
I don't think that it would be correct to call `.toFixed(1)` on the output of `| round` here.  The `round` filter should be outputting a number type, not a string type (`toFixed` outputs a string type).  You can see the problem with this in the following example: 

    {{ 1 + 2.5 | round }}

Currently, this expression outputs to '4', but if `.toFixed(1)` were called on the output of `round` before it returned, the expression would result in '13', because when one of the arguments to `+` is a string, the other argument is coerced to a string as well.

Unfortunately, this is more an issue of the way that number types print in JavaScript, and of the fact that JavaScript only has one number datatype, rather than Python's 2+ number datatypes (`int`, `float`, and then some).  Achieving correspondence between Jinja and Nunjucks on this issue from the Nunjucks side would probably require implementing stand-ins for Python's `int` and `float` datatypes inside Nunjucks, and carrying this differentiation across the entirety of the implementation.  It's a rabbit hole.

The way that I achieved correspondence in this kind of situation is by attacking it from the Jinja side.  Giving Nunjucks pseudo-ints and pseudo-floats so that it matches the behavior of Jinja is much harder than restricting Jinja to using `float` types in most cases, and printing them in a manner consistent with Javascript.  That way, in both Jinja and Nunjucks `{{ 3.4545 | round }}` will output `3`.  If you're interested in this code, we do plan on releasing it soon.

**Comment by carljm** [comment]
Hmm, yeah... I think @legutierr is right, the issue here is the behavior of the underlying numeric types in JS vs Python, and I don't think there's a reasonable fix at the level of the `round` filter; having `round` return a string instead of a number is not an option. Instead, I think if you want fully-consistent string representations of floating-point numbers between Jinja2 and nunjucks, you may need to write your own custom filter to do that and return a string.
