### ISSUE TITLE
Has {% set %} scope been changed within includes?

### ISSUE THREAD

**Issue by johnteh** [mozilla/nunjucks#724]
I need to have unique IDs in my components, so in my template i have set a global variable.

Within my components i increment this variable by 1, so that not matter how many times i use these includes in the template, the ID always gets incremented by 1.

I could increment in the template, but some of these components are nested in other components.

This was working up until updating to the latest nunjucks.

I see scope has changed for macros but no mention of includes.

**Comment by jbmoelker** [comment]
@johnteh could you share which version you were working before and are using now?

For now, an alternative might be using a function or filter to generate a random ID. I'm using this setup:
* [generate random ID](https://github.com/jbmoelker/nunjucks-bootstrap/blob/master/lib/renderer.js#L14)
* [used to give each carousel unique ID](https://github.com/jbmoelker/nunjucks-bootstrap/blob/master/src/media/carousel/carousel.html#L51)

**Comment by johnteh** [comment]
I am currently on nunjucks v.2.4.0.

If i roll back to v2.3.0 then the variables work again. Unfortunate we need to use 2.4.0 because we reuse block names in our templates.

Thank you for the links and code snippets. This looks exactly what i need.

**Comment by carljm** [comment]
@johnteh Yes, in v2.4.0 the scoping was changed so that includes can no longer write to their including scope. This is listed in the changelog for the v2.4.0 release. The change was made in order to match Jinja2 behavior, and because the conceptual model for nunjucks includes is not "preprocessor textual include on the template level", it's "new template render with inherited context, whose results are placed into the including template" (e.g. see the behavior of blocks, where included templates have a separate block structure from the including template).

I guess I considered the previous behavior a clear bug and didn't consider that people might be relying on it; if I'd thought of that I might have delayed the change to 3.0. Sorry about that.
