### ISSUE TITLE
How to "extend" template when rendering from string?

### ISSUE THREAD

**Issue by softshape** [mozilla/nunjucks#730]
{% extends "parent.html" %} seems to be designed for templates rendered from file. Is there any use of it when templates are pre-loaded and rendered from strings? I need to implement templates inheritance together with pre-caching, is there any way to do this?

**Comment by carljm** [comment]
I haven't really played with this, but I think it just depends on what template loaders you configured the environment with; `extends` will try to load a template by name using those loaders. In which case you may as well load and render the initial template via your loader, too, rather than via `renderString`. So yeah, `renderString` doesn't make much sense with template inheritance.

If you need to do something different with template loading (e.g. pre-caching), rather than implement it outside of nunjucks and using `renderString`, I'd consider implementing it as a custom nunjucks template loader instead. You can look at the existing FilesystemLoader and PrecompiledLoader for inspiration. (I'm not sure what motivates your need for pre-caching, but I think given OS-level filesystem caching, template parsing and compiling is likely to be slower than loading from disk, so you may not get a lot of benefit from caching unless you cache the parsed and compiled template code, like the PrecompiledLoader does, rather than just the template source text.)
