### ISSUE TITLE
Logic inside nested macro calls

### ISSUE THREAD

**Issue by roobottom** [mozilla/nunjucks#740]
I have one file that contains several different macros. I've set this up so you can use one inside another like this:

```
{% import './macros.nunjucks' as pattern %}
{{
  pattern.grid([
     pattern.post(data),
     pattern.post(data),
     pattern.post(data),
     pattern.post(data)
  ])      
}}
```

What I'd ideally like to do is something more like this:

```
{% import './macros.nunjucks' as pattern %}
{{
  pattern.grid([
     for data in dataset {
       pattern.post(data)
    }
  ])      
}}
```

Is this ludicrous?

**Comment by carljm** [comment]
It's not ludicrous, but it's well beyond the level of syntactical complexity that I think a templating language should have.

**Comment by ArmorDarks** [comment]
@roobottom Just for the information, you can do it by adding custom function or filter to Nunjucks environment, which will take your arguments and return formed as you need array.

Or you can write more universal filter which will Push anything to new array, and then feed that array to `pattern,grid()`. Here is example of such filter in CoffeeScript: https://github.com/LotusTM/Kotsu/blob/master/tasks/grunt-nunjucks-2-html.coffee#L392

And here is how it should work:

``` jinja
{% import './macros.nunjucks' as pattern %}

{% set dataArray = [] %}

{% for data in dataset %}
  {% set dataArray = dataArray|pushIn(data) %}
{% endfor %}

{{ pattern.grid(dataArray) }}
```

@carljm I don't want to sound offensive, but we really should stop enforcing "our ways of doing things". Just for example, what will be matter of terrible sin for dynamic web templates sometimes is more than good approach for templates of static websites. And by enclosing users with certain conventions by force because otherwise it didn't work for us we not always doing good thing neither, because we not always counting all possible situation and usages. it is especially true for libs which exists in very different environment, and it usage drastically changes depending on that environment. In other words, best practices aren't always "best", they depends on environment.

**Comment by carljm** [comment]
@ArmorDarks I hear your point, and my comment on this ticket was written hurriedly and I mis-spoke; it should say "beyond the level of syntactical complexity that I think _nunjucks_ should have;" there is of course room in the world for a wide variety of templating languages with a wide variety of philosophies.

At the same time, I do think it is part of the job of a maintainer a particular given template language to _have_ a specific philosophy in mind and be consistent with it. Just adding whatever features anyone suggests because "well, it might be useful to someone in some situation" is not a path to a coherent and usable library. My philosophy for nunjucks (which I've been clear about since the day I took on maintainership, since nobody else wanted it :-) ) is that nunjucks should be an excellent JS clone of Jinja2. This feature request does not fit within that goal.

Many of these decisions about which features to include or exclude are judgment calls, and someone has to make them. I'm happy to share (or even give up entirely) that responsibility, if someone else wants it. (But there's a fair amount of work that comes along with it: gardening the issues list, responding to all new issues, and making timely new releases, at minimum).

Thanks for your contributions to nunjucks! I'm always happy to hear your point of view and discuss the pros and cons of any particular issue.

**Comment by ArmorDarks** [comment]
@carljm In some terms I'm glad that I've written such provocative postulate, since, as expected, I've heard some interesting thoughts from you. Thanks :)

However, now I realizing that my terribly poor communication skills revealed once again,

Your position about judgement calls and adding whatever features anybody wants is totally right. I've already supported your position regarding Nunjucks following only ways of Jinja2 in Nunjucks 2.0 discussion. I've already said, that if Nunjucks and Jinja2 can't do something, that issue should be elevated to Jinja2 first, and only then followed by Nunjucks. This is totally fine.

The thing is, that my post wasn't about new features at all. My complain here only about what exactly has been said.

Just compare:

> it's well beyond the level of syntactical complexity that I think a templating language should have.

and

> We don't plan to make it part of Nunjucks core, since Jinja2 doesn't support it. You can achieve similar effect with your own Nunjucks filter. If you think it's viable feature for core, please, elevate it to Jinja2 https://github.com/pallets/jinja/issues. Also, double check, do you really need to do it that way.

Well, it's somehow longer, but I hope that general idea can be catched. Don't take it literally :)

We deny request, but not idea. One of the most important things here is that we have necessary room for implementation, so that developer can achieve this if he really needs it to. We're letting know about our concerns regarding doing this thing, but only lightly. Because we don't know what he's doing there. Maybe he's nailing second nail in his hand, or maybe he's building something, that will revolutionize our ways of thinking. Remember how React started. Who knows.

**Comment by carljm** [comment]
Yep, your point is well-taken. Thanks for raising it. I'll try to do better at communicating in that style.
