### ISSUE TITLE
Alternate solution for nested variables

### ISSUE THREAD

**Issue by fivedoor** [mozilla/nunjucks#779]
Hi there,

I have just started using gulp & nunjucks for tempting and finding it an extremely useful tool.  

I'm trying to solve a problem of calling a module/partial and assigning different values to the attributes each time that it is processed. 

It initially seems like a job for ‘set’ or a for loop but the module will not necessarily be called upon in sequence within the template

Within the module there are attributes assigned to variables. I would like to resolve those variables differently depending on the section the module is being used for. 

A very basic example would be - in an index file I'd have : 

```
{% block content %}

<!-- logo start -->
{% include genericMod %}
<!-- logo end -->

<!-- some other section start -->
{% include someOtherMod %}
<!-- some other section end -->

<!-- hero start -->
{% include genericMod %}
<!-- hero end -->

{% endblock %}
```

And in the genericMod itself-:

```
<tr>
 <td class="full-width-image" align=“{{{{modKey}}.align}}" ><img src=“{{{{modKey}}.src}}" alt=“{{{{modKey}}.alt}}"/></td>
</tr>
```
The kind of functionality I'd like to tap into would be to define a “modKey” i.e. a variable within each variable in the module Then assign that key to the module each time it is called: 

```
<!-- logo start —>
{% logo content %}
{% set modKey = "logo" %}
{% include genericMod %}
{% endblock %}
<!-- logo end -->
```

So the above would first produce: 

```
<tr>
 <td class="full-width-image" align="{{logo.align}}" ><img src="{{logo.src}}" alt="{{logo.alt}}"/></td>
</tr>
```
And when piped through a json file the respective data would be rendered for each attribute variable: 

```
"logo": {
    "alt": "some logo alt text",
    "href": "http://www.someurl.com",
    "align": "left"
  },
 "hero": {
    "alt": "some hero alt text",
    "href": "http://www.someotherurl.com",
    "align": "centre"
  }
```
The problem is the variable within another variable will just throw an error. 
I was hoping there's a way of actually achieving something similar? (Apologies if there is an obvious way to achieve this that I'm missing.)

**Comment by carljm** [comment]
Just assign the actual value of the context var to a common variable name, instead of assigning a string:

```
{% set data = logo %}
{% include oneIncludeFile %}
{% set data = hero %}
{% include otherIncludeFile %}
```

Then within each of those included files you can just reference e.g. `{{ data.alt }}` or `{{ data.href }}`.

Though with this type of pattern (parameterized bits of markup) I recommend using macros rather than includes. Macros are like functions that take arguments, so you could define a macro like:

```
{% macro foo(data) %}
<a href="{{ data.href }}"><img src="{{ data.src }}" alt="{{ data.alt }}" /></a>
{% endmacro %}
```

and then call it like ``{{ foo(logo) }}`` and ``{{ foo(hero) }}`` to pass in different sets of data.

Though typically I'd use multiple separate arguments to the macro rather than a single argument which is an object with various keys, as it makes explicit what data the macro requires.

Hope this helps. BTW, in future please ask usage-type questions on the nunjucks google group mailing list, rather than on GitHub. Thanks!

**Comment by fivedoor** [comment]
That does indeed help - it's exactly what I was trying to get my head around. 
Thanks so much @carljm  
I will keep the usage questions for the google group next time. 
Thanks
