### ISSUE TITLE
How to mark 'safe' strings in inline if?

### ISSUE THREAD

**Issue by softshape** [mozilla/nunjucks#781]
The statement `{{ ' class="current" ' if true else '' }}` produces `class="&quot;current&quot;"`. I tried to play with |safe but without much success. Does is work with inlines? What's the correct way to get `class="current"` with this rule?

**Comment by carljm** [comment]
Either `{{ ' class="current" '|safe if true else '' }}` or `{{ (' class="current" ' if true else '') }}` should work fine, what did you try? `{{ ' class="current" ' if true else ''|safe }}` won't work because the filter pipe binds more tightly than the if-else, you're just marking the empty string safe.

In the future, please ask usage questions on the google groups mailing list, not in a github issue.
