### ISSUE TITLE
Nunjucks with BrowserSync

### ISSUE THREAD

**Issue by amichel86** [mozilla/nunjucks#804]
I am using Nunjucks with BrowserSync, whenever I save a HTML file the browser is refreshed, simple as that. Sometimes when I have a two character word/number or I change a Bootstrap column class (ex: col-12 for col-9) and I save the file, the browser gets refreshed but not the HTML. 

Has anyone encounter this problem too?

(I don't know what causes this problem exactly, but that's how I experienced it. Sometimes it refreshes with the content of a previous save...)

**Comment by dotmagic** [comment]
I'm quite sure this is not related to nunjucks, please check your nunjucks watch task. You dont tell you're using gulp, grunt or pure nodejs.

**Comment by ArmorDarks** [comment]
Also, does your Grunt or Gulp or anything else you use triggers on change of any file re-rendering of all Nunjucks templates, or only changed one?

**Comment by amichel86** [comment]
Forgot to mention that I am using Gulp. Here's a screenshot of the Nunjucks task and watch task. Apparently there's nothing wrong but if you could double check, that'd be great!

![image](https://cloud.githubusercontent.com/assets/5871701/17665278/f4766a7c-62c7-11e6-9559-d7093e956155.png)

**Comment by dotmagic** [comment]
@amichel86 I'm not a browsersync expert, your watch task watch changes in `app/pages` and `app/templates` but the destination seems to be just `app` without a subfolder pages? May this be the problem?

Did you take a look on the browsersync recipes?
https://github.com/Browsersync/recipes/tree/master/recipes/gulp.sass

However. This isn't nunjucks related. I suggestion you may check the above and if you still can't get it working close the issue here and open a new one on browsersync.

**Comment by amichel86** [comment]
Alright, thank you for your time and sorry for the inconvenience, I will look into this! :)
