### ISSUE TITLE
Block scoping is too strict (stricter than Jinja) in 3.0.0.

### ISSUE THREAD

**Issue by jgerigmeyer** [mozilla/nunjucks#906]
There were a number of commits included in 3.0.0 that fixed scoping issues, but now it seems that `{% call %}` blocks no longer have access to variables set in their parent scope. This differs from the Jinja2 implementation.

In Jinja2, the following code:

```django
{% macro inside() %}
  <div>inside: {{ caller() }}</div>
{% endmacro %}

{% macro outside(var) %}
  <div>outside: {{ var }}</div>
  {% call inside() %}
    {{ var }}
  {% endcall %}
{% endmacro %}

{{ outside('foobar') }}
```

Outputs:

```html
<div>outside: foobar</div>
<div>inside: foobar</div>
```

In Nunjucks 3.0.0, the output is:

```html
<div>outside: foobar</div>
<div>inside: </div>
```

See http://jsfiddle.net/jgerigmeyer/mjpbm13j/

**Comment by ChristianAuth** [comment]
We got the same problem here. Not being able to access local variables inside of {% call %} blocks seems to break a lot of standard use cases. 

I would strongly vote to rollback the strict scoping for {% call %} blocks.

**Comment by vecmezoni** [comment]
Introduced in https://github.com/mozilla/nunjucks/commit/429f636bde7a781b98849269560beb69388cba30

**Comment by ArmorDarks** [comment]
Seems to be related to my similar issue https://github.com/mozilla/nunjucks/issues/912

**Comment by paulmsmith** [comment]
This should be fixed but I'd love to [see the PR for adding `embed`](https://github.com/mozilla/nunjucks/pull/814) functionality progressed which would mean a lot of my use of `call` can be dropped entirely.

**Comment by ArmorDarks** [comment]
`embed` isn't option for those, who works within multiple environments.

**Comment by paulmsmith** [comment]
@ArmorDarks I get that, does that mean it's dead as a potential feature for Nunjucks? I think feature parity is important, could it be done as an extension perhaps?

**Comment by ArmorDarks** [comment]
@paulmsmith Well, I'm not a maintainer, I can't tell :)

Personally I'm not very happy with `embed`, since it overlaps with macros. I think that instead macros should be enhanced. However, I understand needs of those, who goes from Swig to Nunjucks and needs `embed`, thus I don't vote against it.

I think for now it wasn't merged only because new maintainers didn't have enough time to review PR. My guess.

**Comment by ArmorDarks** [comment]
Hi guys!

Any updates on this issue?..

**Comment by jgerigmeyer** [comment]
I dug into this for awhile yesterday, but didn't get very far. Reverting the changes to `compiler.js` in #667 fixes this issue, but not surprisingly breaks the added tests #667 was intended to fix. The changes in #791 are also related.

I pushed an initial attempt at https://github.com/oddbird/nunjucks/commit/104c46c0434b1db46d4d5b8086cd14678f2ddcf0 in case that helps someone else. It fixes one of the test cases, but breaks some others.

**Comment by jgerigmeyer** [comment]
I think all of these test cases are already supported by Jinja.

**Comment by ArmorDarks** [comment]
I can only guess, since I never worked with Jinja.

Though, if Jinja works exactly the way all those newer test cases describes, this already means that in Jinja it's impossible to change global variable by macro. Not big loss, though, but still this seem like an oversight in design of the language.

**Comment by ArmorDarks** [comment]
This issue seems to be related too https://github.com/mozilla/nunjucks/issues/679#issuecomment-286447747

**Comment by jgerigmeyer** [comment]
Since we have new maintainers (welcome and thanks, @fdintino!), I'd like to bump this bug again. It's a pretty major bug in v3.0.0, and I wasn't able to figure it out after digging around awhile in the code (https://github.com/mozilla/nunjucks/issues/906#issuecomment-275713585). Many thanks to anyone willing to give it a shot!

**Comment by fdintino** [comment]
I'll try to take a look at this issue over the next weekend.

**Comment by paulmsmith** [comment]
Wondering what the status of this issue is now?

**Comment by ArmorDarks** [comment]
Same thing here... This bug makes Nunjucks 3.0.0 unusable...

**Comment by fdintino** [comment]
@noahlange any chance they your refactoring work addresses this bug?

**Comment by noahlange** [comment]
@fdintino - not at the moment, sorry. 😕

I can do some digging and see if I can track this down.

**Comment by fdintino** [comment]
I have a fix for this. I'll clean it up later today and push it out.

What threw myself (and I'm guessing others as well) is that test the wrong behavior for `{% set %}`, and so fixing this bug was causing those tests to "fail."

**Comment by ArmorDarks** [comment]
@fdintino Nice to hear it! Can you point to that wrong test? Just curious.

**Comment by fdintino** [comment]
@ArmorDarks it was [these two tests](https://github.com/mozilla/nunjucks/blob/5c2bf56820baf66fa41b0ca5ef91e2cdcafddaf4/tests/compiler.js#L1110-L1123). The values returned from jinja2 are `'1'` and `'678afterwards: 5'`, respectively.

**Comment by ArmorDarks** [comment]
@fdintino Hm, looking on those tests I'm starting to doubt that Jinja's behavior is correct. Shouldn't declaration of variable before scope make any changes in that scope propagate to declared in upper scope variable? In other words, current tests behavior seems to be correct.

Is behavior same in Python? I don't have any experience with Python, so I can't check myself.

**Comment by fdintino** [comment]
It's a common misconception that Jinja2 follows the conventions of Python everywhere, but that's not generally true. It supports a subset of python syntax, but template-specific constructs like blocks, macros, includes, template scoping, and the `set` and `call` tags don't have obvious analogous in Python. The Jinja2 docs are pretty explicit in stating that writes with `{% set %}` should not modify variables in the outer scope (with the exception of if/else tags): see the [Jinja2 docs on assignments](http://jinja.pocoo.org/docs/2.9/templates/#assignments), specifically the second section titled “Scoping Behavior.” It's definitely intentional. Since nunjucks lacks a consistent specification for how scope should act (and not unrelatedly there are a lot of bugs with scope) my preference would be to defer to Jinja's behavior generally.

I will note that Twig does not isolate writes inside `{% for %}` blocks, so I'm open to making those an exception the same way `{% if %}` and `{% else %}` tags are. As long as the behavior is well considered.
