### ISSUE TITLE
Question about localisation

### ISSUE THREAD

**Issue by androidlabsmontreal** [mozilla/nunjucks#948]
In the context of templating, is it possible to use nunjucks for a multilingual site so that a change of language link sends you to the same page in the other language rather than send you to the main index page?

**Comment by androidlabsmontreal** [comment]
anyone?

**Comment by ArmorDarks** [comment]
It's not related to Nunjucks itself. Nunjucks is a templating library. It just tells how to render what you're passing to it, and it knows nothing about routes of your application.

What you want to do depends on your environment, since it will determine how exactly routing between locale-specific pages should be done, and for which url which Nunjucks template should be rendered.

If it's happens so that you render with Nunjucks static websites, you can take an example of l10n from [Kotsu](https://github.com/LotusTM/Kotsu).

**Comment by androidlabsmontreal** [comment]
thank you for your input, I will research the matter based on the guidance that you have provided me with.
